### ISSUE TITLE
Views give unexpected results

### ISSUE THREAD

**Issue by giacomogiudice** [emmt/StructuredArrays.jl#3]
Hi, 

I'm getting unexpected when getting a slice using a colon:
```julia
julia> arr = UniformArray(1, 3, 4)
3×4 UniformMatrix{Int64}:
 1  1  1  1
 1  1  1  1
 1  1  1  1

julia> arr[:,2]
1

julia> Matrix(arr)[:,2]
3-element Vector{Int64}:
 1
 1
 1
```
This happens both for `UniformArray` as well as `FastUniformArray`. Interestingly this works for views, but it is slow because it probably falls back to the `AbstractArray` implementation.

**Comment by emmt** [comment]
Sorry for the late answer. I've just tried your example and it worked fine for me. whech version of Julia and of structuredArrays are you using? (respectively 1.9 and 0.2.7 for me).

If you extract a slice with `arr[:,2]` you will create an independent array which is a regular array (hence not a uniform array) but if you are using `view(arr, :, 2)`, then you have a slice sharing its contents with `arr`. 

Extracting a slice (by sub-indexing) of a uniform array as another uniform array would require some work but would perfectly make sense.

**Comment by giacomogiudice** [comment]
Hi Éric,

thank you very much for you reply. Indeed, I had not updated, I was still running `0.2.6`.
It  would be nice that a slice would return a uniform array, if I have time I can take a look into it.

**Comment by emmt** [comment]
I can see that I have made a number of changes related to indexation of uniform arrays between 0.2.6 and 0.2.7. They may explain the first issue you had. For the other point, it would be an imporvement but we hav to investigate a bit. Perhaps it is very easy to do...

**Comment by emmt** [comment]
I have pushed on the master branch, a preliminary version where `A[i...]`, with `A` a uniform array and `i...` sub-array indices, yields a uniform array (or a scalar). You may try it. I am currently generalizing this to all possible types of sub-indices `i...` (as allowed for other array types) and extend this optimization to `view(A, i...)` when `A` is an immutable uniform array. Expect to see a 0.2.8 version of `StructuredArrays` soon. In the mean time, I would appreciate if you could test the master version.

**Comment by emmt** [comment]
That's done (see diff [here](https://github.com/emmt/StructuredArrays.jl/compare/v0.2.7...v0.2.8)). It turns out to yield simpler and yet more general code. I hope it'll behave as you expected. Thanks for the suggestion.

**Comment by giacomogiudice** [comment]
Wow, that's quite an elegant way to handle indexing!

I tested a bit indexing and views. I also ran the following benchmark, with fairly impressive results
```julia
using BenchmarkTools
using StructuredArrays


arr = FastUniformArray(2, 1000, 1000, 1000)

k = rand(axes(arr, 2))
@btime @inbounds sum($arr[:,$k,:])
@btime @inbounds sum(@view $arr[:,$k,:])
@btime @inbounds sum(x -> x÷2, $arr[:,$k,:])
@btime @inbounds sum(x -> x÷2, @view $arr[:,$k,:])
```
On `0.2.7` I get
```
  1.133 ms (2 allocations: 7.63 MiB)
  1.232 ms (0 allocations: 0 bytes)
  1.212 ms (2 allocations: 7.63 MiB)
  1.232 ms (0 allocations: 0 bytes)
```
versus `0.2.8`
```
  4.208 μs (0 allocations: 0 bytes)
  4.208 μs (0 allocations: 0 bytes)
  4.208 μs (0 allocations: 0 bytes)
  4.214 μs (0 allocations: 0 bytes)
```

I'll go ahead and close this issue, thanks!
